server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: ${LOG_FILE:logs/eureka-server.log}

  level:
    root: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
